PREFIX oa:     <http://www.w3.org/ns/oa#>.
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>.
PREFIX schema:  <http://schema.org/> .
PREFIX graphs: <http://exemple.fr/>.
PREFIX para: <http://www.zoomathia.com/PLINE-8-annoteIPL/8/>.

construct { para:195 graphs:hasConcept ?label_concept.}  where {
  ?annotation a oa:Annotation;
              oa:hasBody ?concept;
              oa:hasTarget ?target.
  ?target oa:hasSource para:195.
  ?concept skos:prefLabel ?label_concept.
}